#!/bin/bash
set -e
set -o pipefail

# a heroku CLI wrapper so we can force `heroku run` to always use `--exit-code`

heroku=$HOME/vendor/heroku-toolbelt/bin/heroku

if [[ $# -gt 0 ]]; then
  cmd="$1"; shift

  if [[ "$cmd" == "run" ]] && ( ! echo "$@" | grep -- "--exit-code" 2>&1 >/dev/null ); then
    exec $heroku run --exit-code "$@"
  fi
fi

exec $heroku $cmd "$@"
